// app/[locale]/layout.jsx
import localFont from "next/font/local"
import { Inter } from 'next/font/google';
import { AuthProvider } from '@/contexts/AuthContext';
import i18nConfig from '@/i18nConfig';
import { dir } from 'i18next';
import "./globals.css"

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import TranslationsProvider from "@/components/TranslationsProvider"
import initTranslations from "@/i18n"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

const inter = Inter({ subsets: ['latin'] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

const i18nNamespaces = ['common', 'navbar'];

export default async function RootLayout({ children, params: { locale } }) {
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale} dir={dir(locale)}>
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased  bg-gray-200 dark:bg-gray-900 text-[#032541] dark:text-white`}
      >
        <AuthProvider>
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >
          <main>
            <Navbar />
            <div className="relative min-h-100">
              {children}
              <ToastContainer />
            </div>
            
            <Footer />
          
          </main>
        </TranslationsProvider>
        </AuthProvider>
      </body>
    </html>
  )
}